# Welcome to Jekyll!

# Website settings
title: "ELEVAR"
description: "Página web de ELEVAR"
keywords: "ELEVAR, banderas, astas, patria"
baseurl: "/"
url: "http://elevarbanderas.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'ELEVAR'
  first_name: 'ELEVAR'
  last_name: ''
  email: 'elevarbanderas@gmail.com'
  github_username: 'elevarbanderas'
  twitter_username: 'elevarbanderas'
  instagram_username: 'elevarbanderas'
  head_img: 'static/img/landing/picture.PNG'
  descrip: 'Empresa estable, de propiedad privada y bien financiada de banderas, astas y todo el material patriotico relacionado'

# sections
sections:
  - id: 'about'
    i18n: 'nav.about'
    name: '¿Quiénes somos?'
    tpl: 'about.html'
    css: ''

  - id: 'charlas'
    i18n: 'nav.charlas'
    name: 'Charlas'
    tpl: 'charlas.html'
    css: 'timeline'
    
  - id: 'cursos'
    i18n: 'nav.cursos'
    name: 'Cursos'
    tpl: 'cursos.html'
    css: 'timeline'    
    
  - id: 'olimpico'
    i18n: 'nav.olimpico'
    name: 'Olímpico'
    tpl: 'olimpico.html'
    css: 'timeline'    

  - id: 'labs'
    i18n: 'nav.labs'
    name: 'Laboratorios'
    tpl: 'labs.html'
    css: 'timeline'
    
  - id: 'physik'
    i18n: 'nav.physik'
    name: 'Physik'
    tpl: 'physik.html'
    css: 'timeline'    
    
  - id: 'biospeci'
    i18n: 'nav.biospeci'
    name: 'BIOSPECI'
    tpl: 'biospeci.html'
    css: 'timeline'   
    
  - id: 'ateneo'
    i18n: 'nav.ateneo'
    name: 'Ateneo'
    tpl: 'ateneo.html'
    css: 'timeline'
    
  - id: 'spefi'
    i18n: 'nav.spefi'
    name: 'SPEFI'
    tpl: 'spefi.html'
    css: 'timeline'

  - id: 'foot'
    i18n: 'nav.foot'
    name: ''
    tpl: 'foot.html'
    css: ''


#  - id: 'skills'
#    i18n: 'nav.skills'
#    name: 'Skills'
#    tpl: 'skills.html'
#    css: 'team'

#  - id: 'projects'
#    i18n: 'nav.projects'
#    name: 'Projects'
#    tpl: 'projects.html'
#    css: 'project'

#  - id: 'publications'
#    i18n: 'nav.publications'
#    name: 'Publications'
#    tpl: 'publications.html'
#    css: 'publications'

# localization
languages:
#  - locale: 'en'
#    flag: 'static/img/flags/United-States.png'
  # - locale: 'zh'
  #   flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
  # name: jalpc
  # public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
  # uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
  # uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
  # id: UA-73784599-1

# growingIO
gio:
  # id: a49d4901c7853da9

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

